name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: zidansec/zidansec@master
        with:
          WAKATIME_API_KEY: 29570748-bdb5-4499-bee6-9264d25e04cf
