# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: zidansec
          template: classic
          base: ""
          config_timezone: Asia/Jakarta
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://www.xploit.my.id/feeds/posts/default?alt=rss
